--- 
title: "An introductory course to open science"
author: "Opendoor Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

Greetings, fellow PhD student or open science curious friend!

In this course, we would like to introduce you to the world of open science. Whether you are familiar with some of its concepts and resources or the open science movement doesn’t ring any bells, we believe that what you learn here will be interesting for you and at the same time highly useful for your future career. 

We ourselves are PhD students who firstly met during the course focusing on open and collaborative research. And because we felt that what we learned was very helpful and other students should have an opportunity to get familiar with these concepts too, we decided to create Agape. Agape means wide open, such as open science we want to promote. The word agapē originates from Greek and means love that is unconditional, such as our love for science. Under Agape we aim to disseminate open science between students, starting with this course and continuing with series of workshops where we can learn, exchange our opinions and experiences and together change the future. 

With this course, Agape would like to open doors for you into the world of open science and to introduce various concepts that we think are very important but we were not told about. Whilst we all heard about the scientific integrity and open access publishing at some point of our studies, a domain of open science encompasses a much larger area. Given its extent, this course is by far not covering the whole scope of open science. However, during the course we provide you with useful links to other resources should you wish to learn more and start practising open science. 

The course is structured into chapters that are written to expand on various topics. We think that an order they follow is logical and later chapters are building on knowledge in the previous ones, but you can decide to go through them in whatever order you like by clicking on different chapters in the menu on the left or to return to some of them should you find something is not clear or you forgot in the meantime.  

Your progress throughout the course is tracked. At the end, you can obtain a Certificate of achievement. This will be generated for you automatically and emailed to the email address you use to log into this course. In order to obtain this certificate you’ll need to achieve at least 90% success rate in MCQs and activities at the end of each chapter. You have as many attempts to pass each of them as you want. Once you’re happy with your result you confirm it and it will be saved under your profile until you confirm this for all chapters. After completing the last one, allow it a couple of hours before you receive the certificate.

Should you experience any technical problems or do not receive a certificate email us on 

If you’d like to connect with us or see what’s new you can do so on Twitter           or Instagram          (or any other social media account).

And now, without further delay, let’s quench that thirst for knowledge! 


